---
# tasks file for deploy-stack

- name: Set variables
  set_fact:
    yaml_file: "{{ deploy_stack_stack_file | basename }}"
    stack_name: "{{ (deploy_stack_stack_file | basename | splitext)[0] }}"
  when: deploy_stack_stack_file is defined

- name: Set variables
  set_fact:
    yaml_file: "{{ deploy_stack_stack_name }}.yml"
    stack_name: "{{ deploy_stack_stack_name }}"
  when: deploy_stack_stack_hash is defined

- name: Create the support folder
  file:
    path: "{{ deploy_stack_lib_folder }}"
    state: directory
    mode: 0755

- name: check existence
  command: "docker stack ps {{ stack_name }}"
  changed_when: false
  ignore_errors: true
  register: ps_out

- name: remove file if the file doesn't reflect the real status
  file:
    state: absent
    path: "{{ deploy_stack_lib_folder }}/{{ yaml_file }}"
  when: ps_out is failed

- name: Copy the yaml
  copy:
    src: "{{ deploy_stack_stack_file }}"
    dest: "{{ deploy_stack_lib_folder }}/{{ yaml_file }}"
  register: yamlcopying
  when: deploy_stack_stack_file is defined

# write hash as yaml
- name: Write the yaml
  copy:
    content: "{{ deploy_stack_stack_hash | to_nice_yaml }}"
    dest: "{{ deploy_stack_lib_folder }}/{{ yaml_file }}"
  register: yamlcopying
  when: deploy_stack_stack_hash is defined

- name: remove preexisting stack
  command: "docker stack rm {{ stack_name }}"
  when: 
    - ps_out is succeeded
    - yamlcopying is changed

- name: Check if the network is down
  command: docker network ls
  register: cmd_res
  retries: 15
  delay: 1
  until: cmd_res.stdout_lines | select('search', ' ' + stack_name +'_default') | list | count == 0
  when: 
    - ps_out is succeeded
    - yamlcopying is changed

- name: Deploy the stack
  command: "docker stack deploy --resolve-image never --compose-file {{ deploy_stack_lib_folder }}/{{ yaml_file }} {{ stack_name }}"
  when: yamlcopying.changed
  register: deploy_out
  ignore_errors: true

- name: remove file if something gone wrong
  file:
    state: absent
    path: "{{ deploy_stack_lib_folder }}/{{ yaml_file }}"
  when: deploy_out is failed

- fail:
    msg: "Impossible to deploy the stack {{ deploy_out }}"
  when: deploy_out is failed

